version: "3"

services:
  hello-docker-react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-docker-react
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 8087:3000
    volumes:
      - .:/home/node
